# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PardesCli < Formula
  desc "PARDES CLI — método PARDES como coreógrafo do teu agente de IA."
  homepage "https://www.pardes.pro"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/LeonardoMendoncaDev/pardes-cli/releases/download/v0.0.1/pardes-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "2621a163ebff8d9082bda2200a7a870e9ce8a43c9d39b2b52ae804175c62bc91"

      define_method(:install) do
        bin.install "pardes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/LeonardoMendoncaDev/pardes-cli/releases/download/v0.0.1/pardes-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "524e3f983ff23c5d69aadaa7d5c0a44b35e688b7498f0865257ab5e78c1ff7ab"

      define_method(:install) do
        bin.install "pardes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/LeonardoMendoncaDev/pardes-cli/releases/download/v0.0.1/pardes-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "6711e4dc02b47cda46b35fc159bd710e750125b3bd3492d0a9e2ddfe25ce3ed2"
      define_method(:install) do
        bin.install "pardes"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/LeonardoMendoncaDev/pardes-cli/releases/download/v0.0.1/pardes-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "8b4044507a53987fc9adc504e50372dad53bed0013d3227d7646f75b382838ba"
      define_method(:install) do
        bin.install "pardes"
      end
    end
  end

  test do
    system "#{bin}/pardes", "--version"
  end
end
